name: EPG Combinado

on:
  schedule:
    - cron: '10 22 * * *'  # 00:10 en hora española (CET/CEST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Bash
      run: sudo apt-get install bash

    - name: Run epgprevio.sh
      run: ./epgprevio.sh

    - name: Run epgunido.sh
      run: ./epgunido.sh

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "Actualización diaria de EPG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true  # Continúa aunque haya un error
